Autopark/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as main_urls
from users import urls as users_urls
from main.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('main/', include(main_urls)),
    path('users/', include(users_urls)),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contacts/<str:id>/', contacts, name='contacts'),
    
    path('cars/<int:pk>/', car_detail, name='car_detail'),
    path('cars/', cars, name='cars'),
    path('drivers/', drivers, name='drivers'),
    path('clients/', clients, name='clients'),
    
    path('add_car/', add_car, name='add_car'),
    path('add_driver/', add_driver, name='add_driver'),
    path('add_client/', add_client, name='add_client'),
    
    path('employees/<int:pk>/update/', EmployeeUpdate.as_view(), name='employee-update'),
    path('employees/<int:pk>/delete/', EmployeeDelete.as_view(), name='employee-delete'), 
    path('employees/', EmployeeList.as_view(), name='employee_list'),
    path('employees/<int:pk>/', EmployeeDetail.as_view(), name='employee-detail'),
    path('employee_form/', EmployeeCreate.as_view(), name='employee-form'),
    
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users' # Префекс маршрута

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
]  

main/models.py
from django.db import models
from django.urls import reverse

# 1. Create your models here.
# 2. Create migrations: python manage.py makemigrations
# 3. Migrate: python manage.py migrate


class Driver(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    age = models.IntegerField(verbose_name='Возраст')
    city = models.CharField(max_length=100, verbose_name='Город')
    is_activated = models.BooleanField(verbose_name='Активация')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Человек'
        verbose_name_plural = 'Люди'


class Car(models.Model):
    brand = models.CharField(max_length=30, verbose_name='Марка')
    model = models.CharField(max_length=30, verbose_name='Модель')
    color = models.CharField(max_length=30, verbose_name='Цвет')
    power = models.IntegerField(verbose_name='Мощность')
    year = models.IntegerField(verbose_name='Год')

    def __str__(self):
        return ' '.join([str(self.brand), str(self.model)])

    class Meta:
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'


class Client(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия')
    birthday = models.DateField(verbose_name='Дата рождения')
    age = models.IntegerField(verbose_name='Возраст', null=True)
    city = models.CharField(max_length=30, verbose_name='Город')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Эл. почта')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return ' '.join([self.name, self.last_name])
    
    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Employee(models.Model):
    edu_choises = [('middle', 'среднее'),
                   ('high', 'высшее'),
                   ('professional', 'профессиональное'),
    ]

    firstname = models.CharField(max_length=50, verbose_name='Имя')
    lastname = models.CharField(max_length=50, verbose_name='Фамилия')
    birthday = models.DateField(verbose_name='Дата рождения')
    position = models.CharField(max_length=50,verbose_name='Должность')
    education = models.CharField(max_length=30, choices=edu_choises)

    def __str__(self):
        return ' '.join([str(self.firstname), str(self.lastname)])
    
    def get_absolute_url(self):
        return reverse('main:employee_list')

    # def get_absolute_url(self):
    #     return reverse("author-detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
import datetime
from Autopark.settings import DATE_INPUT_FORMATS

def year_choices():
    return [(r,r) for r in range(1970, datetime.date.today().year+1)]

def current_year():
    return datetime.date.today().year


class CarForm(forms.Form):
    brand = forms.CharField(max_length=50, label='Марка')
    model = forms.CharField(max_length=50, label='Модель')
    color = forms.CharField(max_length=30, label='Цвет', required=False)
    power = forms.IntegerField(label='Мощность (л/с)', required=False, min_value=1, max_value=600)
    year = forms.ChoiceField(label='Год выпуска', choices=year_choices, initial=current_year)


class DriverForm(forms.Form):
    name = forms.CharField(max_length=50, label='Имя водителя')
    age = forms.IntegerField(label='Возраст', min_value=18, max_value=120)
    city = forms.CharField(max_length=50, label='Город', required=False)


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ['age', 'created_at']
        
    
    birthday = forms.DateField(input_formats=DATE_INPUT_FORMATS, label='Дата рождения')
    

main/views.py
import datetime
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.http import HttpResponse
from .forms import CarForm, DriverForm, ClientForm
from .models import *
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.core.paginator import Paginator
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required


menu = [{'title': "О сайте", 'url_name': 'main:about'},
        {'title': "Машины парка", 'url_name': 'main:cars'},
        {'title': "Водители парка", 'url_name': 'main:drivers'},
        {'title': "Клиенты", 'url_name': 'main:clients'},
        {'title': "Сотрудники", 'url_name': 'main:employee_list'},

]

def index(request):
    title = 'Главная страница'
    context = {'title': title, 'menu': menu}
    return render(request, 'main/index.html', context=context)

def about(request):
    title = 'О сайте'
    context = {'title': title, 'menu': menu}
    return render(request, 'main/about.html', context=context)
  
    
def contacts(request, id):
    url_id = id
    name = request.GET.get('name')
    age = request.GET.get('age')
    get_params = {'name': name, 'age': age}
    return HttpResponse(f'Page contacts, url_parametr_id = {url_id}, get_params - {get_params}')

def cars(request):
    title = 'Машины'
    car = Car.objects.all()

    context = {'title': title, 'menu': menu, 'cars': car}
    return render(request, 'main/cars.html', context=context)

@login_required
def drivers(request):
    title = 'Водители'
    context = {'title': title, 'menu': menu}
    return render(request, 'main/drivers.html', context=context)

@login_required
def clients(request):
    title = 'Клиенты'
    clients = Client.objects.all()
    paginator = Paginator(clients, 2)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'title': title, 'menu': menu, 'clients': clients, 'page_obj': page_obj}

    return render(request, 'main/clients.html', context=context)

def add_car(request):
    if request.method =='GET':
        title = 'Добавить машину'
        form = CarForm()
        context = {'title': title, 'menu': menu, 'form': form}
        return render(request, 'main/car_add.html', context=context)
    
    if request.method == 'POST':
        carform = CarForm(request.POST)
        if carform.is_valid():
            car = Car()
            car.brand = carform.cleaned_data['brand']
            car.model = carform.cleaned_data['model']
            car.color = carform.cleaned_data['color']
            car.power = carform.cleaned_data['power']
            car.year = carform.cleaned_data['year']
            car.save()
        return cars(request)

def add_driver(request):
    title='Добавить водителя'
    form = DriverForm()
    context = {'title': title, 'menu': menu, 'form': form}
    return render(request, 'main/driver_add.html', context=context)

def add_client(request):
    title = 'Добавить клиента'
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            age = datetime.date.today().year - form.cleaned_data['birthday'].year
            instance.age = age
            instance.save()
            
            return clients(request)
    else:
        form = ClientForm()
    context = {'title': title, 'menu': menu, 'form': form}
    
    return render(request, 'main/client_add.html', context=context)
    

def car_detail(request, pk):
    car = Car.objects.get(pk=pk)
    title = 'Car detail'
    context = {'object': car, 'title': title}
    
    return render(request, 'main/car_detail.html', context=context)



class EmployeeList(ListView):
    model = Employee
    template_name = 'main/employee_list.html'
    context_object_name = 'employees'
    paginate_by = 2
    
    def get_context_data(self, **kwargs):
        # получение общего контекста из родительского класса
        context = super().get_context_data(**kwargs)
        # изменение родительского контекста (добавление ключей словаря)
        
        context['title'] = 'Сотрудники'
        context["count"] = Employee.objects.count()
        context['menu'] = menu
        return context


class EmployeeDetail(DetailView):
    model = Employee
    template_name = 'main/employee_detail.html'
    context_object_name = 'employee' 

    def get_context_data(self, **kwargs):
        # получение общего контекста из родительского класса
        context = super().get_context_data(**kwargs)
        context['title'] = 'Информация о сотруднике'
        context['menu'] = menu

        return context


class EmployeeCreate(CreateView):
    model = Employee
    fields = '__all__'
    template_name = 'main/employee_form.html'
    

class EmployeeUpdate(UpdateView):
    model = Employee
    fields = '__all__'
    template_name = 'main/employee_update.html'
    

class EmployeeDelete(DeleteView):
    model = Employee
    template_name = 'main/delete.html'
    success_url = reverse_lazy('main:employee_list')
    

    
    


        

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
         <title>{{title}}</title>
</head>
<body>
    {% if user.is_authenticated %}
    <p>Привет, {{user.username}}</p>
    {% endif %}
 
    <ul>
        <li><a href="{% url 'main:index' %}"> Главная </a></li>
 
    </ul>
 
    {% if not user.is_authenticated %}
    <ul>
    <li><a href="{% url 'users:register' %}"> Регистрация </a></li>
    <li><a href="{% url 'users:login' %}"> Войти </a></li>
    </ul>
    {% endif %}
 
    {% if user.is_authenticated %}
    <ul>
    <li><a href="{% url 'users:logout' %}"> Выйти </a></li>
 
    </ul>
    {% endif %}
 
{% block mainmenu %}
<ul>
         {% for m in menu %}
         <h2><li><a href="{% url m.url_name %}">{{m.title}}</a></li></h2>
         {% endfor %}
</ul>
{% endblock mainmenu %}
 
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/car_add.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Добавить машину:
<form action="{% url 'main:add_car' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

main/templates/main/car_detail.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
<ul>
<li>Brand - {{object.brand}}</li>
<li>Model - {{object.model}}</li>
<li>Color - {{object.color}}</li>
<li>Power - {{object.power}}</li>
<li>Year - {{object.year}}</li>
</ul>
{% endblock %}

main/templates/main/car_list.html
<table>
    {% for car in object_list %}
    <tr>
        <td align="center" >{{car.id}}</td>
        <td align="center">
            <a href="{% url 'main:car_detail' pk=car.id %}">{{car.brand}}</a>
        </td>
        
        <td align="center">{{car.model}}</td>
        <td align="center">{{car.color}}</td>
        <td align="center">{{car.power}}</td>
        <td align="center">{{car.year}}</td>
     </tr>
    {% endfor %}
</table>

main/templates/main/client_add.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Добавить клиента:
<form action="{% url 'main:add_client' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

main/templates/main/clients.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>

Клиенты:
<table id="clients" border="1">
    <th>id</th>
    <th>Имя</th>
    <th>Фамилия</th>
    <th>Дата рождения</th>
    <th>Возраст</th>
    <th>Город</th>
    <th>Телефон</th>
    <th>Эл. почта</th>
    <th>Дата создания</th>

    {% for client in page_obj %}
         <tr>
            <td align="center" >{{client.id}}</td>
            <td align="center">{{client.name}}</td>
            <td align="center">{{client.last_name}}</td>
            <td align="center">{{client.birthday}}</td>
            <td align="center">{{client.age}}</td>
            <td align="center">{{client.city}}</td>
            <td align="center">{{client.phone}}</td>
            <td align="center">{{client.email}}</td>
            <td align="center">{{client.created_at}}</td>
         </tr>
{% endfor %}

</table>
<p><a href="{% url 'main:add_client' %}">Добавить клиента</a></p>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Содержимое страницы Контакты
{% endblock %}

main/templates/main/delete.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>

<form method="post">{% csrf_token %}
    <p>Действительно хотите удалить эту запись?</p>
    <input type="submit" value="Удалить">
  </form>

{% endblock content %}

main/templates/main/driver_add.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Добавить водителя:
<form action="{% url 'main:add_driver' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

main/templates/main/drivers.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Содержимое страницы Водитель
<p><a href="{% url 'main:add_driver' %}">Добавить водителя</a></p>
{% endblock %}

main/templates/main/employee_detail.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
<ul>
<li>Имя - {{employee.firstname}}</li>
<li>Фамилия - {{employee.lastname}}</li>
<li>Дата рождения - {{employee.birthday}}</li>
<li>Должность - {{employee.position}}</li>
<li>Образование - {{employee.education}}</li>
</ul>
<a href="{% url 'main:employee-update' pk=employee.id %}"> Изменить </a>
<p><a href="{% url 'main:employee-delete' pk=employee.id %}"> Удалить </a></p>
{% endblock %}

main/templates/main/employee_form.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Добавить сотрудника:
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

main/templates/main/employee_update.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Содержимое страницы Сотрудник

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
Содержимое главной страницы

{% endblock %}